from datetime import date, time, datetime
from typing import Optional
from pydantic import BaseModel, ConfigDict, field_validator, model_validator
import re
from app.schemas.table import TableResponse
from app.schemas.table_session import TableSessionResponse

ALLOWED_STATUSES = ["PENDING", "CONFIRMED", "CHECKED_IN", "CANCELLED", "COMPLETED", "NO_SHOW", "REJECTED"]


class ReservationCreate(BaseModel):
    user_id: Optional[int] = None
    # table_id is NOT included because customer doesn't send it. It will be None initially.
    # reservation_code is generated by backend
    # status is set to PENDING by backend
    reservation_date: date
    start_time: time
    end_time: time
    number_of_guests: int
    customer_name: str
    customer_phone: str
    note: Optional[str] = None

    @field_validator("customer_name")
    @classmethod
    def name_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Customer name must not be empty")
        return v.strip()

    @field_validator("customer_phone")
    @classmethod
    def validate_phone(cls, v: str) -> str:
        v = v.strip()
        # Basic validation for phone number: 9-15 digits, optional leading '+'
        if not re.match(r"^\+?[0-9]{9,15}$", v):
            raise ValueError("Invalid phone number format")
        return v

    @field_validator("number_of_guests")
    @classmethod
    def guest_count_positive(cls, v: int) -> int:
        if v <= 0:
            raise ValueError("Number of guests must be greater than 0")
        return v

    @model_validator(mode='after')
    def check_time_range(self) -> 'ReservationCreate':
        if self.start_time and self.end_time:
            if self.start_time >= self.end_time:
                raise ValueError("end_time must be strictly after start_time")
        return self


class ReservationUpdate(BaseModel):
    table_id: Optional[int] = None
    status: Optional[str] = None
    note: Optional[str] = None
    start_time: Optional[time] = None
    end_time: Optional[time] = None
    number_of_guests: Optional[int] = None
    customer_name: Optional[str] = None
    customer_phone: Optional[str] = None

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in ALLOWED_STATUSES:
            raise ValueError(f"Status must be one of: {', '.join(ALLOWED_STATUSES)}")
        return v

    @field_validator("customer_name")
    @classmethod
    def name_not_empty(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and not v.strip():
            raise ValueError("Customer name must not be empty")
        return v.strip() if v else v

    @field_validator("customer_phone")
    @classmethod
    def validate_phone(cls, v: Optional[str]) -> Optional[str]:
        if v is not None:
            v = v.strip()
            if not re.match(r"^\+?[0-9]{9,15}$", v):
                raise ValueError("Invalid phone number format")
        return v

    @field_validator("number_of_guests")
    @classmethod
    def guest_count_positive(cls, v: Optional[int]) -> Optional[int]:
        if v is not None and v <= 0:
            raise ValueError("Number of guests must be greater than 0")
        return v

    @model_validator(mode='after')
    def check_time_range(self) -> 'ReservationUpdate':
        if self.start_time and self.end_time:
            if self.start_time >= self.end_time:
                raise ValueError("end_time must be strictly after start_time")
        return self


class ReservationResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    user_id: Optional[int] = None
    table_id: Optional[int] = None
    reservation_code: str
    reservation_date: date
    start_time: time
    end_time: time
    number_of_guests: int
    customer_name: str
    customer_phone: str
    note: Optional[str] = None
    rejection_reason: Optional[str] = None
    status: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    
    table: Optional[TableResponse] = None
    session: Optional[TableSessionResponse] = None

class ReservationGuestResponse(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    table_id: Optional[int] = None
    reservation_code: str
    reservation_date: date
    start_time: time
    end_time: time
    number_of_guests: int
    customer_name: str
    customer_phone: str
    note: Optional[str] = None
    rejection_reason: Optional[str] = None
    status: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

    table: Optional[TableResponse] = None

class ReservationAssignTable(BaseModel):
    table_id: int

class ReservationReject(BaseModel):
    reason: str
    
    @field_validator("reason")
    def validate_reason(cls, value):
        val = value.strip()
        if not val:
            raise ValueError("Lý do từ chối không được để trống")
        if len(val) > 500:
            raise ValueError("Lý do từ chối quá dài")
        return val
